# branches to build
branches:
  # whitelist
  only:
    - master

# Operating system (build VM template)
os: Visual Studio 2015

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input


# clone directory
clone_folder: c:\projects\cbLib

platform: x64
configuration: Release

install:
  # by default, all script lines are interpreted as batch

build:
  project: cbProject.sln                    # path to Visual Studio solution or project

# scripts to run before build
before_build:
  - echo Running cmake...
  - cd c:\projects\cbLib\build
  - cmake -G "Visual Studio 14 2015 Win64"